{
    "type": "bundle",
    "id": "bundle--7f595acc-c0a7-467b-bcb6-bb9659f02069",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--0d0df8a1-c36e-47ae-b970-17e547b706af",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-11-04T00:15:47.207177Z",
            "modified": "2023-11-04T00:15:47.207177Z",
            "name": "CVE-2023-41164",
            "description": "In Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri() is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-41164"
                }
            ]
        }
    ]
}