{
    "type": "bundle",
    "id": "bundle--f3afab06-1acc-40fe-bf2d-ff73b7ea87d8",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--5f1711b1-2060-4c98-b1b7-093fcca9e19b",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-06-24T00:05:49.792811Z",
            "modified": "2023-06-24T00:05:49.792811Z",
            "name": "CVE-2023-32414",
            "description": "The issue was addressed with improved checks. This issue is fixed in macOS Ventura 13.4. An app may be able to break out of its sandbox",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-32414"
                }
            ]
        }
    ]
}