{
    "type": "bundle",
    "id": "bundle--c6c7df2b-9b76-4356-9be1-678043fc366f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ea802167-d2b4-4c2c-94ee-0dd93f727be3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-04-16T00:05:18.823617Z",
            "modified": "2023-04-16T00:05:18.823617Z",
            "name": "CVE-2020-27545",
            "description": "libdwarf before 20201017 has a one-byte out-of-bounds read because of an invalid pointer dereference via an invalid line table in a crafted object.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-27545"
                }
            ]
        }
    ]
}