{
    "type": "bundle",
    "id": "bundle--78c5b03f-728d-44c8-876d-a95958272c44",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--fd83cbac-5284-4cda-b526-ea3c5e0ea4c9",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-01-19T00:17:01.432019Z",
            "modified": "2024-01-19T00:17:01.432019Z",
            "name": "CVE-2023-48359",
            "description": "In autotest driver, there is a possible out of bounds write due to improper input validation. This could lead to local denial of service with System execution privileges needed",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-48359"
                }
            ]
        }
    ]
}