{
    "type": "bundle",
    "id": "bundle--a4116c1c-5a88-4d01-a927-df004eb52f24",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--f776f6e2-e25a-4965-b86d-8c0d7ce108a5",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-08-24T00:04:40.613425Z",
            "modified": "2023-08-24T00:04:40.613425Z",
            "name": "CVE-2023-41105",
            "description": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-41105"
                }
            ]
        }
    ]
}