{
    "type": "bundle",
    "id": "bundle--50c9217e-26b2-4dec-b88c-478596afb16f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--90563b34-7cda-4917-8b51-2ac08a7ead9f",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-02-02T00:15:51.725917Z",
            "modified": "2024-02-02T00:15:51.725917Z",
            "name": "CVE-2024-1141",
            "description": "A vulnerability was found in python-glance-store. The issue occurs when the package logs the access_key for the glance-store when the DEBUG log level is enabled.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-1141"
                }
            ]
        }
    ]
}