{
    "type": "bundle",
    "id": "bundle--fd79c02b-020b-4873-b6c4-76c7d5654fcf",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bb6a185d-fc23-4bf0-9005-819ff0218de7",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2023-08-23T00:04:53.688502Z",
            "modified": "2023-08-23T00:04:53.688502Z",
            "name": "CVE-2022-48560",
            "description": "A use-after-free exists in Python through 3.9 via heappushpop in heapq.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-48560"
                }
            ]
        }
    ]
}